### ISSUE TITLE
Furnace in Temporal Mode crashes. (Ticking TE)

### ISSUE THREAD

**Issue by binarybagel** [Lumaceon/ClockworkPhase2#14]
I was testing all features of this mod with a friend and we discovered that the Clockwork Furnace in Temporal Mode crashes the game (using higher tier gears). We tested it with other machines and it seems to be only an issue with the furnace. Here's his crashlog: https://pastebin.com/wFJ5kchX

This is not related to the issue but just a request, could you either add a config to change the spawn coordinates of the crater or make the game automatically execute the Spreadplayers command on startup? We kept spawning inside of the crater and died faster than we were able to escape.

**Comment by Lumaceon** [comment]
The furnace is now fixed in version 0.1.4.

By default, there's code in place to relocate the world spawn away from the crater. If you were spawning there, that's a bug.

I've implemented what is hopefully a fix for 0.1.4. That being said, old worlds will still retain their broken spawn locations. If the problem persists with new worlds, open a new issue and post the world seed.

**Comment by binarybagel** [comment]
Thanks, sorry that I missed out on this update. Another question: Is it safe to add this mod in a modpack even though it is set as Alpha on Curse?

**Comment by Lumaceon** [comment]
The update was _because_ of this report (and a few other bugs), so thank you.

Alpha just means it's a very early release with major potential for bugs (which you saw). It should be compatible with other Forge mods.

**Comment by binarybagel** [comment]
I just thought that the pack might get rejected because the mod doesn't sync across the network. But if that's not a problem, thank you!

**Comment by Lumaceon** [comment]
If by that you mean you're creating a new modpack for other people to download via Curse, no I don't think that'll work. I was referring to dropping it in a pre-existing modpack for personal use.

**Comment by binarybagel** [comment]
Yeah I thought so. I will add alternative recipes and quote out the ones with CP recipe components until this is no longer an alpha mod if Curse rejects my upload this week.
