### ISSUE TITLE
Temporal core feature?

### ISSUE THREAD

**Issue by dylanpiera** [Lumaceon/ClockworkPhase2#5]
It looks amazing. But have you tought about any use for it then looks?

Will it be a portal to a dimension. Or will it be necessary for crafting recipes?

**Comment by dylanpiera** [comment]
I think it could be used as a inworld crafting thing. in combination with the celestial compass

You can put items on the symbols of the compass. Then when right click the middle it will activate the ritual.
And if you have the Temporal core installed it will be faster, Or have more options or something like that. And if you want you can make fancy graphics for it ^^;

**Comment by Lumaceon** [comment]
The temporal core mostly exists for mid-tier crafting purposes. The symbols on the Celestial Compass are for the timezone modules, which all cause area-effects (currently just the fluid storage).
