### ISSUE TITLE
Support for Stellar Sky and its changes to the lunar cycle

### ISSUE THREAD

**Issue by Sunconure11** [Lumaceon/ClockworkPhase2#8]
https://github.com/Abastro/StellarSky

Albeit not overly well known, you might want to add some compatibility for this mod if you want to add back stuff like the celestial compass, as it changes the way lunar cycles work.

**Comment by Lumaceon** [comment]
Mod compatibility is a very low priority right now (unless it causes a crash), but I'll leave this open as a possibility for the future.
